config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("services.urls", namespace="services")),
    path("", include("medicine.urls", namespace="medicine")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from medicine.apps import MedicineConfig

from .views import (AppointmentCreateView, AppointmentListView, CompanyView,
                    ContactsListView, DoctorDetailView, DoctorListView,
                    HomeView)

app_name = MedicineConfig.name

urlpatterns = [
    # Главная страница, о компании, контакты
    path("", HomeView.as_view(), name="home"),
    path("company/", CompanyView.as_view(), name="company"),
    path("contacts/", ContactsListView.as_view(), name="contacts"),
    # Список и создание докторов
    path("medicine/doctor/", DoctorListView.as_view(), name="doctor_list"),
    path("medicine/doctor/<int:pk>/", DoctorDetailView.as_view(), name="doctor_detail"),
    # создание и список записей на прием
    path(
        "medicine/appointment/", AppointmentListView.as_view(), name="appointment_list"
    ),
    path(
        "medicine/appointment/create/",
        AppointmentCreateView.as_view(),
        name="appointment_form",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from services.apps import ServicesConfig
from services.views import ServiceDetailView, ServiceListView

app_name = ServicesConfig.name

urlpatterns = [
    path("service/", ServiceListView.as_view(), name="service_list"),
    path("service/<int:pk>/", ServiceDetailView.as_view(), name="service_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, UserRegisterView,
                         email_verification)

app_name = UsersConfig.name

urlpatterns = [
    # Регистрация/авторизация
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    # выход из системы
    path("logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from config import settings
from services.models import Service


class Doctor(models.Model):
    """Модель доктора"""

    doctor_specialization = [
        ("doctor of functional diagnostics", "Врач функциональной диагностики"),
        ("Radiation diagnostics", "Лучевой диагност"),
        ("A doctor of ultrasound diagnostics", "Врач ультразвуковой диагностики"),
        (
            "Doctor of clinical laboratory diagnostics",
            "Врач клинической лабораторной диагностики",
        ),
    ]

    full_name = models.CharField(max_length=100, verbose_name="Имя и фамилия доктора")
    work_experience = models.PositiveIntegerField(
        verbose_name="стаж работы", blank=True, null=True, default=0
    )
    resume = models.TextField(verbose_name="Резюме доктора")
    avatar = models.ImageField(
        upload_to="medicine/avatars/", verbose_name="Аватарка", null=True, blank=True
    )
    specialization = models.CharField(
        max_length=150,
        choices=doctor_specialization,
        verbose_name="специализация",
        db_index=True,
    )

    class Meta:
        verbose_name = "доктор"
        verbose_name_plural = "доктора"

    def __str__(self):
        return self.full_name


class Company(models.Model):
    """Модель компании"""

    name = models.CharField(max_length=100, verbose_name="Название компании")
    history = models.TextField(verbose_name="История компании")
    mission = models.CharField(max_length=500, verbose_name="Миссия компания")
    values = models.TextField(verbose_name="ценность компании")
    photo = models.ImageField(
        upload_to="medicine/company/", verbose_name="Аватарка", null=True, blank=True
    )
    phone = PhoneNumberField(verbose_name="телефон", blank=True, null=True)
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, verbose_name="Врач", blank=True, null=True
    )
    services = models.ForeignKey(
        to=Service,
        on_delete=models.CASCADE,
        verbose_name="Услуги",
        blank=True,
        null=True,
    )
    email = models.EmailField(
        unique=True, verbose_name="почта компании", blank=True, null=True
    )
    address = models.CharField(
        max_length=400,
        verbose_name="адрес",
        help_text="укажите адрес компании",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компаний"

    def __str__(self):
        return self.name


class Appointment(models.Model):
    """Модель записи на прием"""

    STATUS_CHOICES = [
        ("You have an appointment", "Вы записаны на прием"),
        ("You haven't made an appointment", "Вы не записаны на прием"),
    ]

    status = models.CharField(
        choices=STATUS_CHOICES,
        default="Вы записаны на прием",
        verbose_name="Статус",
        db_index=True,
    )
    appointment_time = models.DateTimeField(
        verbose_name="время",
        help_text="укажите время записи на прием",
    )
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.CASCADE,
        verbose_name="доктор",
        help_text="укажите доктора к которому хотите записаться",
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        null=True,
    )
    response = models.TextField(
        verbose_name="Результаты диагностики", blank=True, null=True
    )

    class Meta:
        verbose_name = "Запись на прием"
        verbose_name_plural = "Записи на прием"

    def __str__(self):
        return f"{self.doctor} : {self.appointment_time}"

medicine/forms.py
from django import forms

from medicine.models import Appointment, Doctor


class DoctorForm(forms.ModelForm):
    """Форма создания доктора"""

    class Meta:
        model = Doctor
        fields = ["full_name", "resume", "specialization", "work_experience"]

    def __init__(self, *args, **kwargs):
        super(DoctorForm, self).__init__(*args, **kwargs)
        self.fields["full_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите имя и фамилию доктора"}
        )
        self.fields["resume"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите резюме"}
        )
        self.fields["specialization"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Выберите специализацию",
            }
        )
        self.fields["work_experience"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Укажите стаж работы в этой сфере",
            }
        )


class AppointmentForm(forms.ModelForm):
    """Форма создания записи на прием"""

    class Meta:
        model = Appointment
        fields = [
            "doctor",
            "appointment_time",
        ]

        widgets = {
            "appointment_time": forms.DateInput(attrs={"type": "datetime-local"})
        }

medicine/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView
from rest_framework.reverse import reverse_lazy
from django.shortcuts import render
from medicine.forms import AppointmentForm
from medicine.models import Appointment, Company, Doctor
from services.models import Service


class HomeView(ListView):
    """Контроллер отображения главной информации"""

    model = Company
    template_name = "medicine/home.html"
    context_object_name = "home"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["home"] = Company.objects.first()
        context["doctor"] = Doctor.objects.all()  # или фильтруй как нужно
        context["service"] = Service.objects.all()

        return context


class CompanyView(ListView):
    """Контроллер отображения информации о компании"""

    model = Company
    template_name = "medicine/company.html"
    context_object_name = "company"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["doctor"] = Doctor.objects.all()  # или фильтруй как нужно
        context["service"] = Service.objects.all()

        return context


class DoctorListView(ListView):
    """Контроллер вывода списка врачей"""

    model = Doctor
    template_name = "medicine/doctor_list.html"
    context_object_name = "doctors"


class DoctorDetailView(DetailView):
    """Контроллер для детального просмотра"""

    model = Doctor
    context_object_name = "doctor"


class AppointmentListView(ListView):
    """Список записей на прием"""

    model = Appointment
    template_name = "medicine/appointment_list.html"
    context_object_name = "appointments"


# LoginRequiredMixin не позволяет неавторизованным пользователям использовать указанные
class AppointmentCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания записи"""

    model = Appointment
    form_class = AppointmentForm  # используем форму для создания записи
    success_url = reverse_lazy("medicine:appointment_list")

    # автоматическое присваивание владельца при создании

    def form_valid(self, form):
        appointment = form.save()
        user = self.request.user
        appointment.owner = user
        appointment.save()
        return super().form_valid(form)


class ContactsListView(ListView):
    model = Company
    template_name = "medicine/contacts.html"
    context_object_name = "contacts"

    def get(self, request, *args, **kwargs):
        company = Company.objects.first()
        address = company.address
        phone = company.phone
        email = company.email
        context = {
            'address': address,
            'phone': phone,
            'email': email # или получи его из модели
        }
        return render(request, 'medicine/contacts.html', context)

medicine/templates/medicine/head_nav/head.html
{% include 'medicine/color_fon/color.html' %}
<div class="container text-primary-emphasis" style="background-color:#AFEEEE;">
    <header class="border-bottom lh-1 py-3" >
        <div class="row flex-nowrap justify-content-between align-items-center" >
            <div class="col-4 pt-1 ">
                <a class="link-secondary text-primary-emphasis" href="#">Subscribe</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-primary-emphasis text-decoration-none">{{ company.name }}</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center text-primary-emphasis">
                <a class="link-secondary" href="#" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                         stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                         viewBox="0 0 24 24"><title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <path d="M21 21l-5.2-5.2"></path>
                    </svg>
                </a>
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <a href="{% url 'medicine:home' %}">
                        <button class="p-2 btn btn-outline-primary" type="submit">Выйти</button>
                    </a>
                </form>
                {% else %}
                <a href="{% url 'users:login' %}">
                    <button class="p-2 btn btn-outline-primary" type="submit">Войти</button>
                </a>
                <a href="{% url 'users:register' %}">
                    <button class="p-2 btn btn-outline-primary" type="submit">Регистрация</button>
                </a>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-3 border-bottom">
        <nav class="nav nav-underline justify-content-between">
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis active " href="{%url 'medicine:home'%}">Главная</a>
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis" href="{%url 'medicine:company'%}">О компании</a>
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis" href="{%url 'services:service_list'%}">Наши услуги</a>
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis" href="{%url 'medicine:contacts'%}">Контакты</a>
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis" href="{%url 'medicine:appointment_list'%}">Ваш профиль</a>
            <a class="nav-item nav-link link-body-emphasis text-primary-emphasis" href="{%url 'medicine:doctor_list'%}">Команда врачей</a>
        </nav>
    </div>
</div>