config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("services.urls", namespace="services")),
    path("", include("medicine.urls", namespace="medicine")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from medicine.apps import MedicineConfig

from .views import (AppointmentCreateView, AppointmentListView, CompanyView,
                    ContactsListView, DoctorDetailView, DoctorListView,
                    HomeView)

app_name = MedicineConfig.name

urlpatterns = [
    # Главная страница, о компании, контакты
    path("", HomeView.as_view(), name="home"),
    path("company/", CompanyView.as_view(), name="company"),
    path("contacts/", ContactsListView.as_view(), name="contacts"),
    # Список и создание докторов
    path("medicine/doctor/", DoctorListView.as_view(), name="doctor_list"),
    path("medicine/doctor/<int:pk>/", DoctorDetailView.as_view(), name="doctor_detail"),
    # создание и список записей на прием
    path(
        "medicine/appointment/", AppointmentListView.as_view(), name="appointment_list"
    ),
    path(
        "medicine/appointment/create/",
        AppointmentCreateView.as_view(),
        name="appointment_form",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, UserRegisterView,
                         email_verification)

app_name = UsersConfig.name

urlpatterns = [
    # Регистрация/авторизация
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    # выход из системы
    path("logout/", LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from config import settings
from services.models import Service


class Doctor(models.Model):
    """Модель доктора"""

    doctor_specialization = [
        ("doctor of functional diagnostics", "Врач функциональной диагностики"),
        ("Radiation diagnostics", "Лучевой диагност"),
        ("A doctor of ultrasound diagnostics", "Врач ультразвуковой диагностики"),
        (
            "Doctor of clinical laboratory diagnostics",
            "Врач клинической лабораторной диагностики",
        ),
    ]

    full_name = models.CharField(max_length=100, verbose_name="Имя и фамилия доктора")
    work_experience = models.PositiveIntegerField(
        verbose_name="стаж работы", blank=True, null=True, default=0
    )
    resume = models.TextField(verbose_name="Резюме доктора")
    avatar = models.ImageField(
        upload_to="medicine/avatars/", verbose_name="Аватарка", null=True, blank=True
    )
    specialization = models.CharField(
        max_length=150,
        choices=doctor_specialization,
        verbose_name="специализация",
        db_index=True,
    )

    class Meta:
        verbose_name = "доктор"
        verbose_name_plural = "доктора"

    def __str__(self):
        return self.full_name


class Company(models.Model):
    """Модель компании"""

    name = models.CharField(max_length=100, verbose_name="Название компании")
    history = models.TextField(verbose_name="История компании")
    mission = models.CharField(max_length=500, verbose_name="Миссия компания")
    values = models.TextField(verbose_name="ценность компании")
    photo = models.ImageField(
        upload_to="medicine/company/", verbose_name="Аватарка", null=True, blank=True
    )
    phone = PhoneNumberField(verbose_name="телефон", blank=True, null=True)
    doctor = models.ForeignKey(
        Doctor, on_delete=models.CASCADE, verbose_name="Врач", blank=True, null=True
    )
    services = models.ForeignKey(
        to=Service,
        on_delete=models.CASCADE,
        verbose_name="Услуги",
        blank=True,
        null=True,
    )
    email = models.EmailField(
        unique=True, verbose_name="почта компании", blank=True, null=True
    )
    address = models.CharField(
        max_length=400,
        verbose_name="адрес",
        help_text="укажите адрес компании",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компаний"

    def __str__(self):
        return self.name


class Appointment(models.Model):
    """Модель записи на прием"""

    STATUS_CHOICES = [
        ("You have an appointment", "Вы записаны на прием"),
        ("You haven't made an appointment", "Вы не записаны на прием"),
    ]

    status = models.CharField(
        choices=STATUS_CHOICES,
        default="Вы записаны на прием",
        verbose_name="Статус",
        db_index=True,
    )
    appointment_time = models.DateTimeField(
        verbose_name="время",
        help_text="укажите время записи на прием",
    )
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.CASCADE,
        verbose_name="доктор",
        help_text="укажите доктора к которому хотите записаться",
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        null=True,
    )
    response = models.TextField(
        verbose_name="Результаты диагностики", blank=True, null=True
    )

    class Meta:
        verbose_name = "Запись на прием"
        verbose_name_plural = "Записи на прием"

    def __str__(self):
        return f"{self.doctor} : {self.appointment_time}"

medicine/forms.py
from django import forms

from medicine.models import Appointment, Doctor


class DoctorForm(forms.ModelForm):
    """Форма создания доктора"""

    class Meta:
        model = Doctor
        fields = ["full_name", "resume", "specialization", "work_experience"]

    def __init__(self, *args, **kwargs):
        super(DoctorForm, self).__init__(*args, **kwargs)
        self.fields["full_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите имя и фамилию доктора"}
        )
        self.fields["resume"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Укажите резюме"}
        )
        self.fields["specialization"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Выберите специализацию",
            }
        )
        self.fields["work_experience"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Укажите стаж работы в этой сфере",
            }
        )


class AppointmentForm(forms.ModelForm):
    """Форма создания записи на прием"""

    class Meta:
        model = Appointment
        fields = [
            "doctor",
            "appointment_time",
        ]

        widgets = {
            "appointment_time": forms.DateInput(attrs={"type": "datetime-local"})
        }

medicine/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView
from rest_framework.reverse import reverse_lazy
from django.shortcuts import render
from medicine.forms import AppointmentForm
from medicine.models import Appointment, Company, Doctor
from services.models import Service


class HomeView(ListView):
    """Контроллер отображения главной информации"""

    model = Company
    template_name = "medicine/home.html"
    context_object_name = "home"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["home"] = Company.objects.first()
        context["doctor"] = Doctor.objects.all()  # или фильтруй как нужно
        context["service"] = Service.objects.all()

        return context


class CompanyView(ListView):
    """Контроллер отображения информации о компании"""

    model = Company
    template_name = "medicine/company.html"
    context_object_name = "company"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["doctor"] = Doctor.objects.all()  # или фильтруй как нужно
        context["service"] = Service.objects.all()

        return context


class DoctorListView(ListView):
    """Контроллер вывода списка врачей"""

    model = Doctor
    template_name = "medicine/doctor_list.html"
    context_object_name = "doctors"


class DoctorDetailView(DetailView):
    """Контроллер для детального просмотра"""

    model = Doctor
    context_object_name = "doctor"


class AppointmentListView(ListView):
    """Список записей на прием"""

    model = Appointment
    template_name = "medicine/appointment_list.html"
    context_object_name = "appointments"


# LoginRequiredMixin не позволяет неавторизованным пользователям использовать указанные
class AppointmentCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания записи"""

    model = Appointment
    form_class = AppointmentForm  # используем форму для создания записи
    success_url = reverse_lazy("medicine:appointment_list")

    # автоматическое присваивание владельца при создании

    def form_valid(self, form):
        appointment = form.save()
        user = self.request.user
        appointment.owner = user
        appointment.save()
        return super().form_valid(form)


class ContactsListView(ListView):
    model = Company
    template_name = "medicine/contacts.html"
    context_object_name = "contacts"

    def get(self, request, *args, **kwargs):
        company = Company.objects.first()
        address = company.address
        phone = company.phone
        email = company.email
        context = {
            'address': address,
            'phone': phone,
            'email': email # или получи его из модели
        }
        return render(request, 'medicine/contacts.html', context)

medicine/templates/medicine/appointment_form.html
{% extends 'medicine/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

medicine/templates/medicine/appointment_list.html
{% extends 'medicine/base.html' %}

{% block title %}Ваши записи на прием{% endblock %}

{% block content %}
<h1>Список записей</h1>
{% if user.is_authenticated %}
<a href="{% url 'medicine:appointment_form' %}" class="btn btn-primary">Записаться на прием</a>
{% else %}
    <p>Для записи рассылки необходима авторизация</p>
    <a href="{% url 'users:login' %}"><button class="p-2 btn btn-outline-primary" type="submit">Войти</button></a>
    <a href="{% url 'users:register' %}"><button class="p-2 btn btn-outline-primary" type="submit">Регистрация</button></a>
{% endif %}
<table class="table">
    <thead>
        <tr>
            <th>Доктор</th>
            <th>Статус</th>
            <th>время</th>
            <th>Результат диагностики</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in object_list %}
        {% if user == appointment.owner %}
        <tr>
            <td>{{ appointment.doctor }}</td>
            <td>{{ appointment.status }}</td>
            <td>{{ appointment.appointment_time }}</td>
            <td>{{ appointment.response }}</td>
        </tr>
        {% endif %}
        {% empty %}
        <tr>
            <td colspan="4">У вас не было записей</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

medicine/templates/medicine/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'medicine/includes_menu/header.html' %}
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Управление рассылками{% endblock %}</title>
    <link href="{% static  'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
    {% include "medicine/head_nav/head.html" %}
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    {% include "medicine/includes_menu/footer.html" %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

medicine/templates/medicine/company.html
{% extends 'medicine/base.html' %}
{% load static %}
{% load my_tags %}
{% include 'medicine/includes_menu/header.html' %}

{% include 'medicine/head_nav/head.html' %}
{% block content %}


<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded ">
        <div class="col-lg-6 px-0">
            <h1 class="display-4 fst-italic text-primary-emphasis">Доверься нам! Мы всё проверим!</h1>
            <p class="lead my-3 text-primary-emphasis">Диагностическое исследование производится лучшим оборудованием,
                лучшими специалистами в своей специализации!</p>
            <p class="lead mb-0 text-primary-emphasis"><a href="{%url 'medicine:doctor_list'%}"
                                                          class="text-primary-emphasis fw-bold">Ознакомиться со
                специалистами...</a></p>
        </div>
    </div>
    {% for com in company %}
    <div class="row">
        <div class="col">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">История создания компании</strong>
                    <h3 class="mb-0 text-primary-emphasis">{{ com.name }}</h3>
                    <ul>
                        <li>{{ com.history }}</li>
                        <li> Находится по адресу: {{ com.address }}</li>
                        <li> Свяжитесь с нами по номеру телефона: {{ com.phone }}
                        или через Email: {{ com.email }}</li>

                    </ul>


                </div>
                <div class="col-auto d-none d-lg-block">
                    <img src="{{ com.photo | media_filter }}" style="border-radius: 20%" class="bd-placeholder-img"
                         width="350" height="400"
                    >
                    <rect width="100%" height="100%" fill="#55595c"></rect>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary-emphasis">Миссия и ценности компании</strong>
                    <h3 class="mb-0 text-primary-emphasis">{{ com.name }}</h3>
                    <ul>
                        <li>
                            Улучши жизнь не только себе но и людям тебя окружающим!
                        </li>
                    </ul>
                </div>
                <div>
                    <img width="500" height="500" style="border-radius: 20%" src="{{ com.photo | media_filter }}">
                </div>
            </div>
        </div>
    </div>

    <div class="row g-5">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom text-primary-emphasis">
                Расскажем об истории компании
            </h3>
            <p align="justify" class="text-primary-emphasis">{{ com.history }}</p>

            <article class="blog-post">
                <h3 class="mb-0 text-primary-emphasis">{{ com.doctor }} </h3>
                <img width="300" height="500" style="border-radius: 20%" src="{{ com.doctor.avatar | media_filter }}">

                <p class="text-primary-emphasis">Основатель - человек с большим сердцем и невероятным медецинским
                    опытом.</p>
                <hr>
                <p align="justify" class="text-primary-emphasis">{{ com.doctor.resume }}</p>
                <h2 class="text-primary-emphasis">Миссия</h2>
                <blockquote class="blockquote">
                </blockquote>
                <p align="justify" class="text-primary-emphasis">{{ com.mission }}</p>
                <hr/>
                <h3  class="text-primary-emphasis">Ценности</h3>
                <ul>
                    <li class="text-primary-emphasis">{{ com.values }}</li>
                </ul>
            </article>

            <nav class="blog-pagination" aria-label="Pagination">
                <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
                <a class="btn btn-outline-secondary rounded-pill disabled">Newer</a>
            </nav>

        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 10rem;">
                <div class="p-4 mb-3 bg-body-tertiary rounded">
                    <h4 class="fst-italic">О нас</h4>
                    <p class="mb-0">Компания использует передовые медицинские технологии </p>
                </div>

                <div>
                    <h4 class="fst-italic">Команда врачей</h4>
                    {% for doc in doctor %}
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative width: 250px; height: 200px">
                        <div class="col d-flex flex-column position-static">
                            <link class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none "
                                  href="#">
                            <img width="170" style="border-radius: 30%"
                                 src="{{ doc.avatar | media_filter }}">
                            <h4 class="mb-0">{{ doc.full_name }}</h4>
                            <p align="justify" >{{ doc.resume }}</p>
                            <link>
                        </div>
                    </div>
                    {% endfor %}

                </div>

                <div class="p-4">
                    <h4 class="fst-italic">Elsewhere</h4>
                    <ol class="list-unstyled">
                        <li><a href="#">GitHub</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</main>
{% endfor %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


<script id="MvYmxvZy8="
        src="https://zmstat.com/?u=https%3A%2F%2Fgetbootstrap.ru%2Fdocs%2F5.3%2Fexamples%2Fblog%2F"></script>
<div id="torrent-scanner-popup" style="display: none;"></div></body></html>
{% endblock %}

medicine/templates/medicine/contacts.html
{% extends 'medicine/base.html' %}
{% block content %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ contact | upper }}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">{{ contact.name | upper }}</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная страница</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ address }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Телефон</td>
                            <td>{{ phone }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Почта</td>
                            <td>{{ email }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                {{ contact.name }}
                <small class="d-block mb-3 text-muted">&copy; 2025</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="https:/sky.pro/">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

medicine/templates/medicine/doctor_detail.html
{% extends 'medicine/base.html' %}
{% load my_tags %}
{% block content %}

<div class="album py-5 bg-body-tertiary ">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
        <div class="col">
          <div class="card shadow-sm ">
            <div class="card-body">
              <p align="justify"  class="card-text services-slider-item card card-gray slick-slide slick-active" data-slick-index="2"
                           aria-hidden="false" style="width: 310px; margin: 5px 10px" tabindex="0" role="tabpanel" id="slick-slide22"
                           aria-describedby="slick-slide-control22">Имя: {{ object.full_name }}</p>
              <p class="card-text services-slider-item card card-gray slick-slide slick-active" data-slick-index="2"
                           aria-hidden="false" style="width: 310px;" tabindex="0" role="tabpanel" id="slick-slide22"
                           aria-describedby="slick-slide-control22">Опыт работы: {{ object.work_experience }}</p>
              <p align="justify" class="card-text services-slider-item card card-gray slick-slide slick-active" data-slick-index="2"
                           aria-hidden="false" style="width: 310px; margin: 5px 10px" tabindex="0" role="tabpanel" id="slick-slide22"
                           aria-describedby="slick-slide-control22">Резюмэ: {{ object.resume }}</p>
              <div class="services-slider-item card card-gray slick-slide slick-current slick-active"
                       data-slick-index="0" aria-hidden="false" style="width: 300px;" tabindex="0" role="tabpanel"
                       id="slick-slide20" aria-describedby="slick-slide-control20">
                        <img src="{{ doctor.avatar | media_filter }}">

              <div class="d-flex justify-content-between align-items-center ">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'medicine:doctor_list' %}" role="button">Вернуться</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

medicine/templates/medicine/doctor_list.html
{% extends 'medicine/base.html' %}
{% load my_tags %}

{% block content %}

<div class="row mb-2">
    <div class="col-md-12">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static ">
                <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <hr>
                        {% for doctor in doctors %}
                        <div class="carousel-item active" >
                            <img src="{{ doctor.avatar| media_filter }}" style="width: 440px; border-radius: 15%" >
                            <h3 class="lead" >{{ doctor.full_name }}</h3>
                            <p align="justify">{{ doctor.resume }}</p>
                        </div>
                        {% endfor %}

                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Предыдущий</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Следующий</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}